# golden-release: 2026.1
[control]
hci01 ansible_host=10.70.0.11
hci02 ansible_host=10.70.0.12
hci03 ansible_host=10.70.0.13

[compute:children]
control

[network]
net01 ansible_host=10.70.0.21
net02 ansible_host=10.70.0.22

[storage]
str01 ansible_host=10.70.0.41

[monitoring]
mon01 ansible_host=10.70.0.51
