# golden-release: 2023.1
# golden-upgrade-to: 2024.1
[control]
c1 ansible_host=10.90.0.11
c2 ansible_host=10.90.0.12
c3 ansible_host=10.90.0.13

[network]
n1 ansible_host=10.90.0.21
n2 ansible_host=10.90.0.22

[compute]
k1 ansible_host=10.90.0.31
k2 ansible_host=10.90.0.32

[storage]
s1 ansible_host=10.90.0.41

[monitoring]
m1 ansible_host=10.90.0.51

[murano]
c1

[sahara]
c2
